# 选择基础镜像
ARG BASE_IMAGE=ubuntu:24.04
# hadolint ignore=DL3006
FROM ${BASE_IMAGE}

# Maintainer
LABEL maintainer="LiuKun<liukunup@outlook.com>"

# Metadata
LABEL org.opencontainers.image.title="DesktopContainer"
LABEL org.opencontainers.image.authors="LiuKun<liukunup@outlook.com>"
LABEL org.opencontainers.image.source="https://github.com/liukunup/desktop-container"
LABEL org.opencontainers.image.licenses="MIT"
LABEL org.opencontainers.image.description="Ubuntu-based remote desktop environment"

ENV DEBIAN_FRONTEND=noninteractive \
    # 用户名/密码 (值为空时，将会自动生成)
    USERNAME="" \
    PASSWORD="" \
    # 默认显示设备
    DISPLAY=":0" \
    # 默认分辨率
    RESOLUTION="1280x720" \
    # 默认颜色深度
    DEPTH="24" \
    # 语言环境
    LANG="C.UTF-8" \
    LC_ALL="C.UTF-8" \
    # 时区设置
    TZ="UTC"

# 拷贝启动脚本
COPY scripts/entrypoint.sh scripts/logger.sh /usr/local/bin/

# 拷贝配置文件
COPY supervisord/my.conf /etc/supervisord.conf

# 安装软件包
RUN apt-get update \
    && apt-get upgrade -y \
    # 安装所需的软件包
    && apt-get install -y --no-install-recommends \
    # CA证书
    ca-certificates \
    # 下载工具
    curl \
    wget \
    # GPG加密工具             
    gnupg \
    # 提供sudo权限管理
    sudo \
    # SSL/TLS工具包
    openssl \
    # SSH服务器
    openssh-server \
    # [Supervisor: A Process Control System](https://supervisord.org/)
    supervisor \
    # Install Xvfb for virtual framebuffer support
    xvfb \
    # D-Bus消息总线系统(X11相关)
    dbus-x11 \
    # VNC服务器，用于远程访问X11会话
    x11vnc \
    # [noVNC: HTML VNC client library and application](https://github.com/novnc/noVNC)
    novnc \
    # [websockify: WebSockets support for any application/server](https://github.com/novnc/websockify)
    websockify \
    # RDP
    xrdp xorg xorgxrdp \
    # 桌面环境 [Xfce Desktop Environment](https://www.xfce.org/)
    xfce4 \
    xfce4-goodies \
    # 音频 [PulseAudio](http://pulseaudio.org/)
    pulseaudio \
    pulseaudio-utils \
    pavucontrol \
    # 字体
    fonts-dejavu \
    fonts-liberation \
    # 远程桌面 [Free Remote Desktop for Everybody - NoMachine](https://www.nomachine.com/)
    && curl -fSL "https://www.nomachine.com/free/linux/64/deb" -o nomachine.deb \
    && dpkg -i nomachine.deb \
    && rm -f nomachine.deb \
    # ----------------------------------------------------
    # === 设置 SSH
    && mkdir -p /var/run/sshd \
    # 生成主机密钥
    && ssh-keygen -A \
    # 修改端口号 & 支持密码登录
    && sed -i \
    -e 's/#Port 22/Port 2222/' \
    -e 's/#PasswordAuthentication yes/PasswordAuthentication yes/' \
    -e 's/#PermitRootLogin prohibit-password/PermitRootLogin no/' \
    -e 's/#X11Forwarding yes/X11Forwarding yes/' \
    /etc/ssh/sshd_config \
    # === 设置 Xfce
    && echo "xfce4-session" > /etc/skel/.xsession \
    && sed -i 's/port=3389/port=3390/g' /etc/xrdp/xrdp.ini \
    && echo "startxfce4" > /etc/xrdp/startwm.sh \
    && chmod +x /etc/xrdp/startwm.sh \
    # === 设置 NoMachine 的 node.cfg
    && cp /usr/NX/etc/node.cfg /usr/NX/etc/node.cfg.bak \
    && sed -i \
    -e "s|^DefaultDesktopCommand.*|DefaultDesktopCommand \"/usr/bin/startxfce4\"|" \
    -e "s|^AvailableSessionTypes.*|AvailableSessionTypes unix-remote,unix-console,unix-default,unix-application,physical-desktop,shadow,unix-xsession-default,unix-xdm,SSH|" \
    -e "s|^CommandStartGnome.*|#&|" \
    -e "s|^#DefaultXSession.*|DefaultXSession /usr/bin/startxfce4|" \
    /usr/NX/etc/node.cfg \
    # === 设置 NoMachine 的 server.cfg
    && cp /usr/NX/etc/server.cfg /usr/NX/etc/server.cfg.bak \
    && sed -i \
    -e "s|#EnableClipboard both|EnableClipboard both|g" \
    /usr/NX/etc/server.cfg \
    # ----------------------------------------------------
    # 赋予脚本执行权限
    && chmod +x /usr/local/bin/entrypoint.sh \
    && chmod +x /usr/local/bin/logger.sh \
    # 清理缓存
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

# 暴露端口
# - 2222: SSH远程访问
# - 4000: NoMachine NX协议
# - 3390: RDP远程桌面
# - 5900: VNC协议
# - 6080: NoVNC Web访问
EXPOSE 2222 4000 3390 5900 6080

ENTRYPOINT [ "/usr/local/bin/entrypoint.sh" ]

CMD [ "desktop" ]